/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : AppClass.sm
 */


/* Test */


#include "AppClass.h"
#include "AppClass_sm.h"

#define getOwner(fsm) (fsm)->_owner



static void AppClassState_EOS(struct AppClassContext *const fsm)
{
    getState(fsm)->Default(fsm);
}

static void AppClassState_One(struct AppClassContext *const fsm)
{
    getState(fsm)->Default(fsm);
}

static void AppClassState_Unknown(struct AppClassContext *const fsm)
{
    getState(fsm)->Default(fsm);
}

static void AppClassState_Zero(struct AppClassContext *const fsm)
{
    getState(fsm)->Default(fsm);
}

static void AppClassState_Default(struct AppClassContext *const fsm)
{
    State_Default(fsm);
}

#define Map1_Start_EOS AppClassState_EOS
#define Map1_Start_One AppClassState_One
#define Map1_Start_Unknown AppClassState_Unknown
#define Map1_Start_Zero AppClassState_Zero
#define Map1_Start_Default AppClassState_Default
#define Map1_Zeros_EOS AppClassState_EOS
#define Map1_Zeros_One AppClassState_One
#define Map1_Zeros_Unknown AppClassState_Unknown
#define Map1_Zeros_Zero AppClassState_Zero
#define Map1_Zeros_Default AppClassState_Default
#define Map1_Ones_EOS AppClassState_EOS
#define Map1_Ones_One AppClassState_One
#define Map1_Ones_Unknown AppClassState_Unknown
#define Map1_Ones_Zero AppClassState_Zero
#define Map1_Ones_Default AppClassState_Default
#define Map1_OK_EOS AppClassState_EOS
#define Map1_OK_One AppClassState_One
#define Map1_OK_Unknown AppClassState_Unknown
#define Map1_OK_Zero AppClassState_Zero
#define Map1_OK_Default AppClassState_Default
#define Map1_Error_EOS AppClassState_EOS
#define Map1_Error_One AppClassState_One
#define Map1_Error_Unknown AppClassState_Unknown
#define Map1_Error_Zero AppClassState_Zero
#define Map1_Error_Default AppClassState_Default
#define Map1_DefaultState_EOS AppClassState_EOS
#define Map1_DefaultState_One AppClassState_One
#define Map1_DefaultState_Unknown AppClassState_Unknown
#define Map1_DefaultState_Zero AppClassState_Zero

#undef Map1_Start_EOS
static void Map1_Start_EOS(struct AppClassContext *const fsm)
{
    struct AppClass *ctxt = getOwner(fsm);

    clearState(fsm);
    AppClass_Acceptable(ctxt);
    setState(fsm, &Map1_OK);
}

#undef Map1_Start_One
static void Map1_Start_One(struct AppClassContext *const fsm)
{

    setState(fsm, &Map1_Ones);
}

#undef Map1_Start_Unknown
static void Map1_Start_Unknown(struct AppClassContext *const fsm)
{

    setState(fsm, &Map1_Error);
}

#undef Map1_Start_Zero
static void Map1_Start_Zero(struct AppClassContext *const fsm)
{

    setState(fsm, &Map1_Zeros);
}

const struct AppClassState Map1_Start = {
    Map1_Start_EOS,
    Map1_Start_One,
    Map1_Start_Unknown,
    Map1_Start_Zero,
    Map1_Start_Default,
    0
};

#undef Map1_Zeros_EOS
static void Map1_Zeros_EOS(struct AppClassContext *const fsm)
{
    struct AppClass *ctxt = getOwner(fsm);

    clearState(fsm);
    AppClass_Acceptable(ctxt);
    setState(fsm, &Map1_OK);
}

#undef Map1_Zeros_One
static void Map1_Zeros_One(struct AppClassContext *const fsm)
{

    setState(fsm, &Map1_Ones);
}

#undef Map1_Zeros_Unknown
static void Map1_Zeros_Unknown(struct AppClassContext *const fsm)
{

    setState(fsm, &Map1_Error);
}

#undef Map1_Zeros_Zero
static void Map1_Zeros_Zero(struct AppClassContext *const fsm)
{

    setState(fsm, &Map1_Zeros);
}

const struct AppClassState Map1_Zeros = {
    Map1_Zeros_EOS,
    Map1_Zeros_One,
    Map1_Zeros_Unknown,
    Map1_Zeros_Zero,
    Map1_Zeros_Default,
    1
};

#undef Map1_Ones_EOS
static void Map1_Ones_EOS(struct AppClassContext *const fsm)
{
    struct AppClass *ctxt = getOwner(fsm);

    clearState(fsm);
    AppClass_Acceptable(ctxt);
    setState(fsm, &Map1_OK);
}

#undef Map1_Ones_One
static void Map1_Ones_One(struct AppClassContext *const fsm)
{

    setState(fsm, &Map1_Ones);
}

#undef Map1_Ones_Unknown
static void Map1_Ones_Unknown(struct AppClassContext *const fsm)
{

    setState(fsm, &Map1_Error);
}

#undef Map1_Ones_Zero
static void Map1_Ones_Zero(struct AppClassContext *const fsm)
{

    setState(fsm, &Map1_Error);
}

const struct AppClassState Map1_Ones = {
    Map1_Ones_EOS,
    Map1_Ones_One,
    Map1_Ones_Unknown,
    Map1_Ones_Zero,
    Map1_Ones_Default,
    2
};

const struct AppClassState Map1_OK = {
    Map1_OK_EOS,
    Map1_OK_One,
    Map1_OK_Unknown,
    Map1_OK_Zero,
    Map1_OK_Default,
    3
};

#undef Map1_Error_EOS
static void Map1_Error_EOS(struct AppClassContext *const fsm)
{
    struct AppClass *ctxt = getOwner(fsm);
    const struct AppClassState* EndStateName = getState(fsm);

    clearState(fsm);
    AppClass_Unacceptable(ctxt);
    setState(fsm, EndStateName);
}

#undef Map1_Error_One
static void Map1_Error_One(struct AppClassContext *const fsm)
{

}

#undef Map1_Error_Unknown
static void Map1_Error_Unknown(struct AppClassContext *const fsm)
{

}

#undef Map1_Error_Zero
static void Map1_Error_Zero(struct AppClassContext *const fsm)
{

}

const struct AppClassState Map1_Error = {
    Map1_Error_EOS,
    Map1_Error_One,
    Map1_Error_Unknown,
    Map1_Error_Zero,
    Map1_Error_Default,
    4
};

#ifdef NO_APPCLASS_SM_MACRO
void AppClassContext_Init(struct AppClassContext *const fsm, struct AppClass *const owner)
{
    FSM_INIT(fsm, &Map1_Start);
    fsm->_owner = owner;
}

void AppClassContext_EOS(struct AppClassContext *const fsm)
{
    const struct AppClassState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "EOS");
    state->EOS(fsm);
    setTransition(fsm, NULL);
}

void AppClassContext_One(struct AppClassContext *const fsm)
{
    const struct AppClassState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "One");
    state->One(fsm);
    setTransition(fsm, NULL);
}

void AppClassContext_Unknown(struct AppClassContext *const fsm)
{
    const struct AppClassState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "Unknown");
    state->Unknown(fsm);
    setTransition(fsm, NULL);
}

void AppClassContext_Zero(struct AppClassContext *const fsm)
{
    const struct AppClassState* state = getState(fsm);

    assert(state != NULL);
    setTransition(fsm, "Zero");
    state->Zero(fsm);
    setTransition(fsm, NULL);
}
#endif

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
